globals:
  enable_debug: false
  enable_economy: true
  use_aegis_system: false
  
groups:
  name_pattern: "^[A-Za-z0-9]{4,16}$"
  tag_pattern: "^[A-Z]{2,3}$"
  
  announce_group_creation: true
  announce_group_deletion: true
  announce_group_relation: true
  
  reputation_max: 8
  reputation_min: -4
  reputation_cost_claim: 1
  reputation_cost_aegis: 16
  reputation_increase_delay: 600
  reputation_on_death: -2
  
  aeigs_base: IRON_BLOCK
  aegis_antenna: IRON_FENCE
  aegis_topper: GOLD_BLOCK
  aegis_signal_on: REDSTONE_TORCH_ON
  aegis_signal_off: REDSTONE_TORCH_OFF
  aegis_antenna_min: 4
  aegis_raidus_per_height: 4
  aegis_materials:
    STONE: 2
    LEATHER: 4
    IRON_INGOT: 8
    GOLD_INGOT: 16
    OBSIDIAN: 32
    DIAMOND: 64
  
  econ_cost_create: 100.0
  econ_cost_claim: 60.0
  econ_reward_unclaim: 40.0
  econ_cost_name: 0.0
  econ_cost_tag: 0.0
  econ_cost_desc: 0.0
  econ_cost_motd: 0.0
  econ_cost_sethome: 0.0
  subgroups:
    econ_cost_create: 10.0
    econ_reward_delete: 5.0
    econ_cost_name: 0.0
    econ_cost_addperm: 0.0
    econ_cost_takeperm: 0.0
    econ_cost_prefix: 0.0
  
  containers:
  - CHEST
  - TRAPPED_CHEST
  - FURNACE
  - BURNING_FURANCE
  - ANVIL
  - BREWING_STAND
  - HOPPER
  - DROPPER
  - DISPENSER
  useable:
  - LEVER
  - WOODEN_DOOR
  - IRON_DOOR
  - TRAP_DOOR
  - DIODE_BLOCK_ON
  - DIODE_BLOCK_OFF
  - REDSTONE_COMPARATOR_ON
  - REDSTONE_COMPARATOR_OFF
  - WOOD_BUTTON
  - STONE_BUTTON
  - WOOD_PLATE
  - STONE_PLATE
  - GOLD_PLATE
  - IRON_PLATE
  - SOIL
  - DIRT
  right_clickable:
  - INK_SACK
  - FLINT_AND_STEEL
  - ENDERPEARL
  - EYE_OF_ENDER
  left_clickable:
  