main: me.capit.urbanization.Urbanization
version: 1.00R01
name: Urbanization

author: Wehttam664
softdepend: ['TagAPI','Vault']

commands:
  urbanization:
    description: Basic Urbanization command.
    usage: '/urbanization help'
    aliases: ['urban','u','group','g', 'f']

permissions:
  urbanization.*:
    description: Global Urbanization permission.
    children:
      - urbanization.kit
      - urbanization.static
  urbanization.kit.player
    description: Player permission kit.
    children:
      - urbanization.group.create
      - urbanization.group.claim
      - urbanization.group.disband
      - urbanization.group.invite
      - urbanization.group.join
      - urbanization.group.modify
      - urbanization.group.sethome
      - urbanization.group.home
      - urbanization.group.unclaim
      - urbanization.group.info
